services:
  auth_server:
    build:
      dockerfile: .docker/Dockerfile
      context: ../
      target: development
    container_name: auth-server
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db
      - redis
  # https://habr.com/ru/articles/578744/
  postgres_db:
    image: postgres:14
    container_name: postgres-auth
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
    volumes:
      - db:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U worker -d app" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379'
volumes:
  db:
    driver: local
